---
- name: Wordpress | Nginx | Figure out PHP FPM socket location
  shell: basename $( ls /usr/sbin/php-fpm*)
  register: 'php_ver'

- name: Wordpress | Nginx | Copy virtual host configuration file
  template:
    src: "nginx-vhost.j2"
    dest: "/etc/nginx/sites-available/{{ wp_sitename }}"
    owner: root
    group: root
    mode: 0644

- name: WordPress | Nginx | Symlink virtual host configuration file from sites-available to sites-enabled
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ wp_sitename }}"
    dest: "/etc/nginx/sites-enabled/{{ wp_sitename }}"
    owner: root
    group: root
    mode: 0644
